title:             don't reboot
email:             spunkzwy@gmail.com
description:       不要重启
author:            spunkzwy
baseurl:           ""
url:               "http://labsday.com"

# Social Profiles
twitter_username:  spunkzwy
github_username:   weiyu10
facebook_username: spunkzwy

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
